# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "801e6eeb5d03d24e1e0b3e13d6f0a305"
application_url = "https://example.com"
embedded = true
name = "bbox-mono-pay"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
